"""The drift test. Fails when README.md's generated tables disagree with tables.py.

WHAT THIS DOES NOT DO: re-run the sweep. It compares the committed README against
the runs recorded under results/, so it catches a hand-edited table, a stale table, and a regenerated
sweep whose README was never updated. It cannot catch a wrong sweep - test_resolve.py
and test_decide.py cover the code that produced those numbers.

test_the_drift_test_can_actually_fail is the one to keep alive. A comparison test that
compares nothing passes forever, which is exactly how the first closure audit got
shipped.
"""
import io

import pytest

import tables


def readme():
    return io.open(tables.README, encoding="utf-8").read()


def prose():
    """The README with every run of whitespace collapsed. A claim in the prose can
    sit either side of a line break - these paragraphs are hand-wrapped and rewrap
    whenever a word changes - so a literal substring search is not stable. Tables
    are still compared against readme() verbatim, where the layout is the point.
    """
    return " ".join(readme().split())


def block(name, table):
    return f"<!-- generated by tables.py: {name} -->\n{table}\n{tables.END}"


def test_every_generated_block_appears_in_the_readme_verbatim():
    text = readme()
    for name, table in tables.blocks(tables.load()):
        assert text.count(block(name, table)) == 1, (
            f"README.md's {name} table disagrees with tables.py - "
            f"run: python tables.py --write"
        )


def test_the_drift_test_can_actually_fail():
    """Move one recorded number and the block must stop matching. If blocks() returned
    nothing, or rendered from the README rather than the sweep, the test above would
    pass unconditionally and prove nothing at all."""
    recorded = tables.load()
    sweep = recorded["sweep"]
    sweep["results"][sweep["write_policy"]][0]["f1"] = 0.5
    changed = dict(tables.blocks(recorded))["policy-comparison"]
    assert changed not in readme()


def test_there_is_a_block_for_every_table_the_readme_marks_as_generated():
    assert len(tables.blocks(tables.load())) == readme().count(tables.END) == 10


def test_a_rendered_table_is_aligned():
    """Column widths are computed over the header and every row, so each line of a
    table is the same length. Checked here because a terminal paste cannot be trusted
    to preserve trailing spaces."""
    for name, table in tables.blocks(tables.load()):
        assert len({len(line) for line in table.split("\n")}) == 1, name


def test_no_merges_reports_a_dash_rather_than_zero_correct():
    """Zero correct out of zero merges is not a finding, it is the definition of a
    matching: closure over one is the identity function. A 0 there would read as
    evidence for the same claim the number cannot speak to."""
    data = tables.load()
    wanted = f"| {tables.DISPLAY[data['sweep']['write_policy']]}"
    table = dict(tables.blocks(data))["closure-cost"]
    row = next(line for line in table.split("\n") if line.startswith(wanted))
    assert row.split("|")[-2].strip() == "-"


def test_a_policy_with_no_readme_name_is_refused(monkeypatch):
    monkeypatch.delitem(tables.DISPLAY, "mutual best")
    with pytest.raises(SystemExit):
        tables.load()


def test_the_marker_path_and_the_header_path_agree():
    """First splice finds a table by a predicate on its header row; the second finds
    the markers the first one left. Two code paths, and if they disagreed the drift
    test would fail on every run for a reason unrelated to any number."""
    table = "| policy | x |\n|--------|---|\n| a      | b |"
    lines = ["intro", "| policy | old |", "|--------|-----|", "| a | old |", "outro"]

    def matches(line):
        return line.startswith("| policy")

    once = tables.splice(lines, "demo", table, matches)
    assert tables.splice(once, "demo", table, matches) == once
    assert (once[0], once[-1]) == ("intro", "outro")


def test_two_candidate_headers_are_refused():
    with pytest.raises(SystemExit):
        tables.splice(
            ["| policy | a |", "| policy | b |"], "demo", "x",
            lambda line: line.startswith("| policy"),
        )


def cell_named(table, name):
    """First column matched exactly. "all features" is a prefix of "all features +
    volume veto", so startswith would pick the wrong row."""
    return next(l for l in table.split("\n") if l.split("|")[1].strip() == name)


def test_the_ablation_delta_is_measured_before_rounding():
    data = tables.load()
    recorded = data["ablation"]
    reference = recorded["results"][recorded["reference"]]["f1"]
    shipped = recorded["results"][recorded["shipped"]]["f1"]
    honest = f"{shipped - reference:+.3f}"
    naive = f"{round(shipped, 3) - round(reference, 3):+.3f}"
    assert honest != naive, "this data can no longer tell the two apart"
    table = dict(tables.blocks(data))["ablation"]
    row = cell_named(table, tables.FEATURE_SETS[recorded["shipped"]])
    assert row.split("|")[-2].strip() == honest


def test_the_reference_row_carries_no_delta():
    data = tables.load()
    table = dict(tables.blocks(data))["ablation"]
    row = cell_named(table, tables.FEATURE_SETS[data["ablation"]["reference"]])
    assert row.split("|")[-2].strip() == "-"


def test_every_scheme_block_py_measures_reaches_the_readme():
    """The hand-typed table showed four of the six schemes. Omitting a row is
    the same failure as mistyping one, and it is the failure this table was
    generated to fix, so the row count is pinned to what block.py recorded."""
    data = tables.load()
    table = dict(tables.blocks(data))["blocking"]
    rows = [l for l in table.split("\n") if l.startswith("|") and "---" not in l]
    assert len(rows) == len(data["blocking"]["order"]) + 1


def test_the_bold_recall_is_the_shipped_k_not_the_best_one():
    """Three schemes tie at 1.000, so bolding the maximum would be arbitrary and
    would move on its own if a larger k ever won. The bold marks what ships."""
    data = tables.load()
    table = dict(tables.blocks(data))["blocking"]
    bold = [l for l in table.split("\n") if "**" in l]
    assert len(bold) == 1
    assert bold[0].split("|")[1].strip() == tables.SCHEMES[data["blocking"]["shipped"]]


def test_the_recorded_runs_agree_on_the_blocking_k():
    """block.py and ablate.py each choose k independently. If one of them moves,
    the README's tables quietly stop describing the same pipeline."""
    runs = {n: r["k"] for n, r in tables.load().items() if "k" in r}
    assert len(runs) >= 2, f"only {sorted(runs)} declare a k"
    assert len(set(runs.values())) == 1, runs


NUMBERS = {2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six", 7: "Seven",
           8: "Eight", 9: "Nine", 10: "Ten", 11: "Eleven"}


def test_the_readme_states_how_many_of_its_tables_are_generated():
    """That paragraph is the README's own claim about how much of itself is
    checked, and it has already been wrong once - it said six hand-typed tables
    and then listed five. Generating another table must break this test rather
    than quietly leaving a smaller number in print."""
    wanted = f"{NUMBERS[len(tables.BLOCKS)]} tables are generated"
    assert wanted in prose(), wanted


def test_the_readme_prose_about_one_to_one_matches_the_recorded_run():
    """volume_feature.py measures two policies; the README tabulates one and puts
    the other in a sentence - all four configurations identical, 0.997 F1, no
    false positives, not one differing decision. Nothing generated covers that."""
    data = tables.load()["volume"]
    paired = data["policies"][data["paired"]]
    printed = {f"{run['f1']:.3f}" for run in paired.values()}
    assert len(printed) == 1, paired
    assert {run["false_positives"] for run in paired.values()} == {0}
    assert all(c["fixed"] == c["broken"] == 0 for c in data["changes"].values())
    assert f"{printed.pop()} F1" in prose()


def test_the_volume_conflict_figures_in_the_prose_are_the_recorded_ones():
    """'fires on 134 of 3,750 candidate pairs with 0 true matches among them' -
    three hand-typed numbers in the sentence carrying the whole case for the veto,
    so they are checked against the run rather than trusted."""
    data = tables.load()["volume"]
    assert data["conflicts_true"] == 0
    wanted = f"{data['conflicts']:,} of {data['candidate_pairs']:,} candidate pairs"
    assert wanted in prose(), wanted


def test_every_generated_table_renders_every_row_its_run_recorded():
    """Silently dropping a row reads as coverage while hiding the same defect as
    mistyping one, and both hand-typed blocking tables did it. Every builder
    that iterates a run's "order" must render all of it, so a table added later
    is covered by this without anyone remembering to write a test.
    """
    data = tables.load()
    rendered = dict(tables.blocks(data))
    checked = 0
    for name, source, _, _ in tables.BLOCKS:
        if source == "sweep":
            continue
        rows = [l for l in rendered[name].split("\n")
                if l.startswith("|") and "---" not in l]
        assert len(rows) == len(data[source]["order"]) + 1, name
        checked += 1
    assert checked >= 4, checked
def test_the_abt_buy_neighbour_counts_are_exactly_k_per_right_record():
    """Every row keeps right_records x k pairs - 1,092 x 20 = 21,840 - so no Buy
    record ever loses a neighbour to a collision. If blocking started returning
    fewer, recall would fall and the table would still look entirely plausible.
    """
    data = tables.load()["abt_blocking"]
    for k in data["neighbours"]:
        run = data["results"][f"k = {k}"]
        assert run["pairs"] == data["right_records"] * k, (k, run["pairs"])
def test_recall_does_not_fall_as_k_grows_in_either_corpus():
    """The k+1 neighbour set contains the k one, so recall cannot decrease. It is
    what makes a blocking table readable as a curve, and checking the shape of
    both recorded runs beats checking numbers I typed from either of them.
    """
    data = tables.load()
    for source, template in (("blocking", "nearest neighbours k={}"),
                             ("abt_blocking", "k = {}")):
        run = data[source]
        recalls = [run["results"][template.format(k)]["recall"]
                   for k in run["neighbours"]]
        assert recalls == sorted(recalls), (source, recalls)
        assert len(recalls) >= 5, source
def test_the_abt_buy_corpus_figures_in_the_prose_are_the_recorded_ones():
    """Four hand-typed numbers introducing the benchmark, each anchored on one
    following word rather than on the whole sentence, which rewraps.
    """
    data = tables.load()["abt_blocking"]
    for wanted in (f"{data['left_records']:,} Abt",
                   f"{data['right_records']:,} Buy",
                   f"{data['true_pairs']:,} true pairs",
                   f"{data['possible_pairs']:,} possible"):
        assert wanted in prose(), wanted
def test_the_sparsity_comparison_measures_both_corpora_the_same_way():
    """This sentence read "0.093% positive, against 16% in the generated
    benchmark" for weeks. The 0.093% was true pairs over all possible pairs; the
    16% was true pairs over the 3,750 that survive blocking. Pre-blocking against
    post-blocking, published as a 170x difference in sparsity. Measured the same
    way the two corpora are 0.093% and 0.094% - so both rates are computed here
    from the same denominator, and the README must print both.
    """
    data = tables.load()
    rates = {}
    for source in ("abt_blocking", "blocking"):
        run = data[source]
        rates[source] = 100 * run["true_pairs"] / run["possible_pairs"]
    assert abs(rates["abt_blocking"] - rates["blocking"]) < 0.01, rates
    for rate in rates.values():
        assert f"{rate:.3f}%" in prose(), rate
def test_the_blocking_gap_between_the_two_corpora_is_the_recorded_one():
    """What the generalisation claim rests on now that the sparsity contrast is
    gone: k = 5 recalls every true pair in the generated benchmark and 0.977
    here, and an exact key recalls 0.235 there against 0.015 here. Both runs
    list their exact-key scheme first, so neither internal name is typed twice.
    """
    data = tables.load()
    books, abt = data["blocking"], data["abt_blocking"]
    assert f"{books['results'][books['shipped']]['recall']:.3f}" == "1.000"
    assert f"{abt['results']['k = 5']['recall']:.3f} of them here" in prose()
    pair = (f"{books['results'][books['order'][0]]['recall']:.3f} there against "
            f"{abt['results'][abt['order'][0]]['recall']:.3f} here")
    assert pair in prose(), pair
def test_the_two_scripts_that_fit_the_same_model_agree_in_print():
    """ablate.py and volume_feature.py fit the same model on the same split and
    each publish an F1 for it. They agree to three decimals but NOT bit for bit -
    0.9774011299435029 against ...28 - because one computes 2PR/(P+R) directly and
    the other goes through sklearn. Compare what is printed, not the float."""
    data = tables.load()
    ablation = data["ablation"]["results"]
    volume = data["volume"]
    tabulated = volume["policies"][volume["tabulated"]]
    for there, here in ((data["ablation"]["reference"], volume["order"][0]),
                        (data["ablation"]["shipped"], volume["shipped"])):
        mine, theirs = ablation[there]["f1"], tabulated[here]["f1"]
        assert f"{mine:.3f}" == f"{theirs:.3f}", (there, here, mine, theirs)
        assert abs(mine - theirs) < 1e-9, (there, here, mine, theirs)

def test_both_abt_buy_scripts_measure_the_same_blocking_recall():
    """abt_buy.py sweeps k through one block.py entry point; match_abt_buy.py
    builds its candidate table through another, at k = 10. Two code paths,
    one quantity - if they ever disagree, one of them is not blocking the way
    the README says. Compared as printed plus a tolerance, never with ==:
    ablate.py and volume_feature.py already differ in the last digit.
    """
    data = tables.load()
    blocking, classifier = data["abt_blocking"], data["abt_classifier"]
    swept = blocking["results"]["k = %d" % classifier["blocking_k"]]
    assert f"{swept['recall']:.3f}" == f"{classifier['blocking_recall']:.3f}"
    assert abs(swept["recall"] - classifier["blocking_recall"]) < 1e-9
    assert swept["pairs"] == classifier["candidate_pairs"]
def test_the_two_abt_buy_scripts_agree_on_the_recall_ceiling():
    """Both derive it from truth_pairs independently, and both used to print
    it as a typed literal. The key names differ between the two recordings
    (rights_ / right_), which is why this bridge is written down.
    """
    data = tables.load()
    blocking, classifier = data["abt_blocking"], data["abt_classifier"]
    assert (blocking["rights_with_several_partners"]
            == classifier["right_with_several_partners"])
    assert (f"{blocking['recall_ceiling']:.3f}"
            == f"{classifier['recall_ceiling']:.3f}")
    assert abs(blocking["recall_ceiling"] - classifier["recall_ceiling"]) < 1e-9
def test_the_abt_buy_test_fold_figures_in_the_prose_are_the_recorded_ones():
    """Four numbers in the sentence above the table, all of which were typed."""
    run = tables.load()["abt_classifier"]
    text = prose()
    assert f"Test fold: {run['test_pairs']:,} candidate pairs" in text
    assert f"{run['test_true']} true pairs reached the matcher" in text
    assert f"{run['truth_in_test']} exist in the fold" in text
    assert f"already lost {run['blocking_lost']} before scoring" in text
def test_exactly_two_cells_are_bold_in_the_abt_buy_classifier_table():
    """The paragraph under this table turns on the two maxima sitting in
    different rows; tables.abt_classifier refuses to render otherwise. This
    checks the rendered table really shows two bold cells in two rows, so the
    refusal cannot quietly become unreachable.
    """
    rendered = tables.abt_classifier(tables.load()["abt_classifier"])
    bold = [line for line in rendered.split("\n") if "**" in line]
    assert len(bold) == 2, rendered
    assert sum(line.count("**") for line in bold) == 4, rendered

def test_the_abt_buy_ablation_is_measured_against_the_shipped_feature_set():
    """The whole table changes meaning with its baseline. It was published
    against a ten-feature model that had already been dropped, which inverted
    every win count in it while leaving every mean correct - so no comparison
    of F1 values could have caught it. This pins the reference to the set the
    pipeline actually fits, and the diagnostic set to being one larger.
    """
    run = tables.load()["abt_features"]
    assert run["reference"] == "all features"
    assert run["sizes"][run["reference"]] + 1 == run["sizes"]["all + description_known"]
    for key in ("pair", "one_to_one"):
        reference = run["layers"][key][run["reference"]]
        assert reference["wins"] is None and reference["p"] is None
def test_the_ablation_win_counts_cannot_exceed_the_number_of_splits():
    """wins + losses <= splits, the remainder being exact ties. Would catch a
    resample loop that ran a different number of times than the header claims,
    which no F1 comparison could see either.
    """
    run = tables.load()["abt_features"]
    checked = 0
    for layer in run["layers"].values():
        for name, row in layer.items():
            if row["wins"] is None:
                continue
            assert row["wins"] + row["losses"] <= run["splits"], name
            assert 0.0 <= row["p"] <= 1.0, name
            assert row["worst"] <= row["mean"] <= row["best"], name
            checked += 1
    assert checked >= 14
def test_the_abt_buy_ablation_prose_numbers_are_the_recorded_ones():
    """Every figure in the two paragraphs under that table."""
    run = tables.load()["abt_features"]
    pair, one = run["layers"]["pair"], run["layers"]["one_to_one"]
    splits, text = run["splits"], prose()
    char_pair, char_one = pair["character similarity only"], one["character similarity only"]
    assert f"{char_pair['wins']} wins in {splits} paired splits, p {char_pair['p']:.3f}" in text
    assert f"takes only {char_one['wins']} of {splits}" in text
    price_pair, price_one = pair["text + price"], one["text + price"]
    assert f"same story, {price_pair['wins']} of {splits} against {price_one['wins']} of {splits}" in text
    extra, extra_one = pair["all + description_known"], one["all + description_known"]
    assert (f"adding it back wins {extra['wins']} of {splits} at the pair layer "
            f"(p {extra['p']:.3f}) and {extra_one['wins']} of {splits} at the "
            f"one-to-one layer (p {extra_one['p']:.3f})") in text
    reference = run["reference"]
    gap_pair = pair[reference]["mean"] - char_pair["mean"]
    gap_one = one[reference]["mean"] - char_one["mean"]
    assert f"gap is {gap_pair:.3f} F1 at the pair layer and {gap_one:.3f} at the" in text
    spread = [row["sd"] for layer in run["layers"].values() for row in layer.values()]
    assert f"sd {min(spread):.3f} to {max(spread):.3f}" in text
def test_the_two_abt_buy_model_runs_share_a_candidate_table():
    """abt_buy_features.py builds its table through match_abt_buy, so if these
    disagree the ablation is describing a different corpus than the classifier
    table three sections above it.
    """
    data = tables.load()
    for key in ("blocking_k", "candidate_pairs"):
        assert data["abt_features"][key] == data["abt_classifier"][key], key

def test_the_readme_explains_the_subset_whose_mean_beats_the_full_model():
    """text + price has a higher mean F1 than the full feature set and still
    loses most splits. That is the clearest single argument in the repo for
    counting wins rather than comparing means, and it is also the line in that
    table a reader is most likely to report as a mistake, so both halves of it
    are pinned: the means in that order, and the losing win count.
    """
    run = tables.load()["abt_features"]
    pair = run["layers"]["pair"]
    subset, reference = pair["text + price"], pair[run["reference"]]
    assert subset["mean"] > reference["mean"]
    assert subset["wins"] * 2 < run["splits"]
    text = prose()
    assert f"higher than the full model's, {subset['mean']:.3f}" in text
    assert f"against {reference['mean']:.3f}, and it still wins under half" in text

def test_the_shipped_books_configuration_is_the_best_one_measured():
    """If some other row ever scores a higher F1 than the configuration the
    pipeline runs, the table is quietly advertising a better option that the
    code declines to take. tables.classifier refuses to render in that case;
    this asserts the same thing against the recording. The second half pins
    the direction of the trade the prose describes: the tuned row does win on
    precision, so "scored worse" is only true of F1 and recall.
    """
    run = tables.load()["match"]
    assert run["shipped"] in run["order"]
    top = max(row["f1"] for row in run["results"].values())
    assert run["results"][run["shipped"]]["f1"] >= top - 1e-12
    assert run["results"]["tuned"]["precision"] > run["results"][run["shipped"]]["precision"]
def test_the_readme_end_to_end_recall_is_the_recorded_one():
    """The headline number for the whole books pipeline."""
    end = tables.load()["match"]["end_to_end"]
    assert f"**{end['found']} of {end['truth_in_test']} = {end['recall']:.3f}**" in prose()
def test_the_readme_tuned_threshold_trade_is_the_recorded_one():
    run = tables.load()["match"]
    shipped, tuned = run["results"][run["shipped"]], run["results"]["tuned"]
    text = prose()
    assert f"({run['tuned_threshold']:.3f}, chosen on the training fold)" in text
    assert (f"buys {tuned['precision'] - shipped['precision']:.3f} precision for "
            f"{shipped['recall'] - tuned['recall']:.3f} recall") in text
    assert f"falls from {shipped['f1']:.3f} to {tuned['f1']:.3f}" in text
def test_the_books_recordings_agree_on_the_split_and_the_candidate_table():
    """Every books recording declaring one of these keys has to agree with
    match.py, since they all build the same candidate table from the same seed
    and split it the same way. This is the third leg of the cross-check:
    ablate.py and volume_feature.py already agree in print, and match.py is
    the script whose numbers the README quotes as headline results. Compared
    by key presence rather than by a hardcoded list of sources, so a new
    recording joins the check by declaring the key.
    """
    runs = tables.load()
    run = runs["match"]
    shared = ("candidate_pairs", "train_pairs", "test_pairs", "test_true", "seed", "k")
    checked = 0
    for name, other in runs.items():
        if name == "match" or name.startswith("abt") or not isinstance(other, dict):
            continue
        for key in shared:
            if key in other and key in run:
                assert other[key] == run[key], f"{name}.{key}"
                checked += 1
    assert checked >= 6

def test_the_ablation_reference_is_the_unvetoed_classifier_from_match():
    """ablate.py refits the model for every subset and never applies the
    volume veto, so its reference row is match.py's "classifier at 0.5" and
    not the shipped "+ volume veto" row. The two agree bit for bit, which is
    only possible if both scripts fit the same model on the same split - the
    third leg of the shipped-configuration cross-check. Compared formatted
    first, because exact float equality across scripts is not something to
    assert blind, and then exactly, because here it does hold.
    """
    data = tables.load()
    ablation = data["ablation"]
    reference = ablation["results"][ablation["reference"]]
    unvetoed = data["match"]["results"]["classifier"]
    shipped = data["match"]["results"][data["match"]["shipped"]]
    for key in ("precision", "recall", "f1"):
        assert f"{reference[key]:.3f}" == f"{unvetoed[key]:.3f}", key
        assert abs(reference[key] - unvetoed[key]) < 1e-9, key
    assert reference["f1"] < shipped["f1"]
    wanted = f"reads {reference['f1']:.3f} rather than the {shipped['f1']:.3f} bolded above"
    assert wanted in prose(), wanted
def test_the_blocking_recording_agrees_with_match_on_the_shipped_scheme():
    """block.py sweeps k and match.py runs one of them. The row block.py marks
    as shipped has to be the one match.py built its candidate table from, or
    the blocking recall the README quotes belongs to a different k than the
    pipeline uses.
    """
    data = tables.load()
    blocking, run = data["blocking"], data["match"]
    row = blocking["results"][blocking["shipped"]]
    assert str(run["k"]) in blocking["shipped"]
    assert row["pairs"] == run["candidate_pairs"]
    assert abs(row["recall"] - run["blocking_recall"]) < 1e-9

def test_the_sweep_reproduces_match_on_the_seed_they_share():
    """sweep.py's first seed is match.SEED, and "threshold only" at a flat 0.5
    with the veto applied is the configuration match.py ships. Two scripts, two
    separate fits, one shared seed: the rows have to agree bit for bit. The
    other two policies have to disagree, or the sweep is not measuring three
    different things and its bands mean nothing.
    """
    data = tables.load()
    sweep, run = data["sweep"], data["match"]
    shipped = run["results"][run["shipped"]]
    index = sweep["seeds"].index(run["seed"])
    row = sweep["results"]["threshold only"][index]
    for key in ("precision", "recall", "f1"):
        assert f"{row[key]:.3f}" == f"{shipped[key]:.3f}", key
        assert abs(row[key] - shipped[key]) < 1e-9, key
    assert sweep["threshold"] == run["threshold"]
    assert sweep["candidate_pairs"] == run["candidate_pairs"]
    differ = [name for name in sweep["results"] if name != "threshold only"
              and abs(sweep["results"][name][index]["f1"] - shipped["f1"]) > 1e-9]
    assert len(differ) == len(sweep["results"]) - 1, differ
    assert f"all {run['candidate_pairs']} pairs" in prose()
def test_the_readme_sweep_band_for_the_shipped_row_is_the_recorded_one():
    """The classifier table's third row is one split, and the README says so by
    quoting the band the 20-split sweep found for the same policy. All three
    figures are derived here, so a re-run that moves the median cannot leave
    the sentence behind. The median is computed by hand rather than imported so
    the even-length case is visible: 20 splits average the middle two.
    """
    data = tables.load()
    sweep = data["sweep"]
    scores = sorted(row["f1"] for row in sweep["results"]["threshold only"])
    shipped = data["match"]["results"][data["match"]["shipped"]]["f1"]
    assert len(scores) == len(sweep["seeds"])
    half = len(scores) // 2
    if len(scores) % 2:
        median = scores[half]
    else:
        median = (scores[half - 1] + scores[half]) / 2
    assert scores[-1] >= shipped - 1e-9
    wanted = (f"{scores[-1]:.3f} is the **top** of its range: median "
              f"{median:.3f}, range {scores[0]:.3f} to {scores[-1]:.3f}")
    assert wanted in prose(), wanted
