"""The drift test. Fails when README.md's generated tables disagree with tables.py.

WHAT THIS DOES NOT DO: re-run the sweep. It compares the committed README against
the runs recorded under results/, so it catches a hand-edited table, a stale table, and a regenerated
sweep whose README was never updated. It cannot catch a wrong sweep - test_resolve.py
and test_decide.py cover the code that produced those numbers.

test_the_drift_test_can_actually_fail is the one to keep alive. A comparison test that
compares nothing passes forever, which is exactly how the first closure audit got
shipped.
"""
import io

import pytest

import tables


def readme():
    return io.open(tables.README, encoding="utf-8").read()


def block(name, table):
    return f"<!-- generated by tables.py: {name} -->\n{table}\n{tables.END}"


def test_every_generated_block_appears_in_the_readme_verbatim():
    text = readme()
    for name, table in tables.blocks(tables.load()):
        assert text.count(block(name, table)) == 1, (
            f"README.md's {name} table disagrees with tables.py - "
            f"run: python tables.py --write"
        )


def test_the_drift_test_can_actually_fail():
    """Move one recorded number and the block must stop matching. If blocks() returned
    nothing, or rendered from the README rather than the sweep, the test above would
    pass unconditionally and prove nothing at all."""
    recorded = tables.load()
    sweep = recorded["sweep"]
    sweep["results"][sweep["write_policy"]][0]["f1"] = 0.5
    changed = dict(tables.blocks(recorded))["policy-comparison"]
    assert changed not in readme()


def test_there_is_a_block_for_every_table_the_readme_marks_as_generated():
    assert len(tables.blocks(tables.load())) == readme().count(tables.END) == 5


def test_a_rendered_table_is_aligned():
    """Column widths are computed over the header and every row, so each line of a
    table is the same length. Checked here because a terminal paste cannot be trusted
    to preserve trailing spaces."""
    for name, table in tables.blocks(tables.load()):
        assert len({len(line) for line in table.split("\n")}) == 1, name


def test_no_merges_reports_a_dash_rather_than_zero_correct():
    """Zero correct out of zero merges is not a finding, it is the definition of a
    matching: closure over one is the identity function. A 0 there would read as
    evidence for the same claim the number cannot speak to."""
    data = tables.load()
    wanted = f"| {tables.DISPLAY[data['sweep']['write_policy']]}"
    table = dict(tables.blocks(data))["closure-cost"]
    row = next(line for line in table.split("\n") if line.startswith(wanted))
    assert row.split("|")[-2].strip() == "-"


def test_a_policy_with_no_readme_name_is_refused(monkeypatch):
    monkeypatch.delitem(tables.DISPLAY, "mutual best")
    with pytest.raises(SystemExit):
        tables.load()


def test_the_marker_path_and_the_header_path_agree():
    """First splice finds a table by a predicate on its header row; the second finds
    the markers the first one left. Two code paths, and if they disagreed the drift
    test would fail on every run for a reason unrelated to any number."""
    table = "| policy | x |\n|--------|---|\n| a      | b |"
    lines = ["intro", "| policy | old |", "|--------|-----|", "| a | old |", "outro"]

    def matches(line):
        return line.startswith("| policy")

    once = tables.splice(lines, "demo", table, matches)
    assert tables.splice(once, "demo", table, matches) == once
    assert (once[0], once[-1]) == ("intro", "outro")


def test_two_candidate_headers_are_refused():
    with pytest.raises(SystemExit):
        tables.splice(
            ["| policy | a |", "| policy | b |"], "demo", "x",
            lambda line: line.startswith("| policy"),
        )


def cell_named(table, name):
    """First column matched exactly. "all features" is a prefix of "all features +
    volume veto", so startswith would pick the wrong row."""
    return next(l for l in table.split("\n") if l.split("|")[1].strip() == name)


def test_the_ablation_delta_is_measured_before_rounding():
    data = tables.load()
    recorded = data["ablation"]
    reference = recorded["results"][recorded["reference"]]["f1"]
    shipped = recorded["results"][recorded["shipped"]]["f1"]
    honest = f"{shipped - reference:+.3f}"
    naive = f"{round(shipped, 3) - round(reference, 3):+.3f}"
    assert honest != naive, "this data can no longer tell the two apart"
    table = dict(tables.blocks(data))["ablation"]
    row = cell_named(table, tables.FEATURE_SETS[recorded["shipped"]])
    assert row.split("|")[-2].strip() == honest


def test_the_reference_row_carries_no_delta():
    data = tables.load()
    table = dict(tables.blocks(data))["ablation"]
    row = cell_named(table, tables.FEATURE_SETS[data["ablation"]["reference"]])
    assert row.split("|")[-2].strip() == "-"


def test_every_scheme_block_py_measures_reaches_the_readme():
    """The hand-typed table showed four of the six schemes. Omitting a row is
    the same failure as mistyping one, and it is the failure this table was
    generated to fix, so the row count is pinned to what block.py recorded."""
    data = tables.load()
    table = dict(tables.blocks(data))["blocking"]
    rows = [l for l in table.split("\n") if l.startswith("|") and "---" not in l]
    assert len(rows) == len(data["blocking"]["order"]) + 1


def test_the_bold_recall_is_the_shipped_k_not_the_best_one():
    """Three schemes tie at 1.000, so bolding the maximum would be arbitrary and
    would move on its own if a larger k ever won. The bold marks what ships."""
    data = tables.load()
    table = dict(tables.blocks(data))["blocking"]
    bold = [l for l in table.split("\n") if "**" in l]
    assert len(bold) == 1
    assert bold[0].split("|")[1].strip() == tables.SCHEMES[data["blocking"]["shipped"]]


def test_the_recorded_runs_agree_on_the_blocking_k():
    """block.py and ablate.py each choose k independently. If one of them moves,
    the README's tables quietly stop describing the same pipeline."""
    runs = {n: r["k"] for n, r in tables.load().items() if "k" in r}
    assert len(runs) >= 2, f"only {sorted(runs)} declare a k"
    assert len(set(runs.values())) == 1, runs


NUMBERS = {2: "Two", 3: "Three", 4: "Four", 5: "Five", 6: "Six", 7: "Seven"}


def test_the_readme_states_how_many_of_its_tables_are_generated():
    """That paragraph is the README's own claim about how much of itself is
    checked, and it has already been wrong once - it said six hand-typed tables
    and then listed five. Generating another table must break this test rather
    than quietly leaving a smaller number in print."""
    wanted = f"{NUMBERS[len(tables.BLOCKS)]} tables are generated"
    assert wanted in readme(), wanted
