"""The drift test. Fails when README.md's sweep tables disagree with tables.py.

WHAT THIS DOES NOT DO: re-run the sweep. It compares the committed README against
results/sweep.json, so it catches a hand-edited table, a stale table, and a regenerated
sweep whose README was never updated. It cannot catch a wrong sweep - test_resolve.py
and test_decide.py cover the code that produced those numbers.

test_the_drift_test_can_actually_fail is the one to keep alive. A comparison test that
compares nothing passes forever, which is exactly how the first closure audit got
shipped.
"""
import io

import pytest

import tables


def readme():
    return io.open(tables.README, encoding="utf-8").read()


def block(name, table):
    return f"<!-- generated by tables.py: {name} -->\n{table}\n{tables.END}"


def test_every_generated_block_appears_in_the_readme_verbatim():
    text = readme()
    for name, table in tables.blocks(tables.load()):
        assert text.count(block(name, table)) == 1, (
            f"README.md's {name} table disagrees with tables.py - "
            f"run: python tables.py --write"
        )


def test_the_drift_test_can_actually_fail():
    """Move one recorded number and the block must stop matching. If blocks() returned
    nothing, or rendered from the README rather than the sweep, the test above would
    pass unconditionally and prove nothing at all."""
    recorded = tables.load()
    recorded["results"][recorded["write_policy"]][0]["f1"] = 0.5
    changed = dict(tables.blocks(recorded))["policy-comparison"]
    assert changed not in readme()


def test_there_is_a_block_for_every_table_the_readme_marks_as_generated():
    assert len(tables.blocks(tables.load())) == readme().count(tables.END) == 3


def test_a_rendered_table_is_aligned():
    """Column widths are computed over the header and every row, so each line of a
    table is the same length. Checked here because a terminal paste cannot be trusted
    to preserve trailing spaces."""
    for name, table in tables.blocks(tables.load()):
        assert len({len(line) for line in table.split("\n")}) == 1, name


def test_no_merges_reports_a_dash_rather_than_zero_correct():
    """Zero correct out of zero merges is not a finding, it is the definition of a
    matching: closure over one is the identity function. A 0 there would read as
    evidence for the same claim the number cannot speak to."""
    data = tables.load()
    wanted = f"| {tables.DISPLAY[data['write_policy']]}"
    table = dict(tables.blocks(data))["closure-cost"]
    row = next(line for line in table.split("\n") if line.startswith(wanted))
    assert row.split("|")[-2].strip() == "-"


def test_a_policy_with_no_readme_name_is_refused(monkeypatch):
    monkeypatch.delitem(tables.DISPLAY, "mutual best")
    with pytest.raises(SystemExit):
        tables.load()


def test_the_marker_path_and_the_header_path_agree():
    """First splice finds a table by a predicate on its header row; the second finds
    the markers the first one left. Two code paths, and if they disagreed the drift
    test would fail on every run for a reason unrelated to any number."""
    table = "| policy | x |\n|--------|---|\n| a      | b |"
    lines = ["intro", "| policy | old |", "|--------|-----|", "| a | old |", "outro"]

    def matches(line):
        return line.startswith("| policy")

    once = tables.splice(lines, "demo", table, matches)
    assert tables.splice(once, "demo", table, matches) == once
    assert (once[0], once[-1]) == ("intro", "outro")


def test_two_candidate_headers_are_refused():
    with pytest.raises(SystemExit):
        tables.splice(
            ["| policy | a |", "| policy | b |"], "demo", "x",
            lambda line: line.startswith("| policy"),
        )
